const SIGNIN_USER_REQUEST = 'SIGNIN_USER_REQUEST'
const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE'

const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST'
const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'

const SIGNOUT_USER = 'SIGNOUT_USER'

export { SIGNOUT_USER, SIGNIN_USER_REQUEST, SIGNIN_USER_SUCCESS, SIGNIN_USER_FAILURE, SIGNUP_USER_REQUEST, SIGNUP_USER_SUCCESS, SIGNUP_USER_FAILURE }